import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget1488/generated/GeneratedRectangle364Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/get_startapp/generatedwidget1488/generated/GeneratedWidget1501.dart';
import 'package:flutterapp/get_startapp/generatedwidget1488/generated/GeneratedWidget1489.dart';
import 'package:flutterapp/get_startapp/generatedwidget1488/generated/GeneratedWidget1495.dart';

/* Frame 成績彈出式選單
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget1488 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 152.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 90, 200, 250),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.868421052631579;

                  final double height =
                      constraints.maxHeight * 0.21921182266009853;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06578947368421052,
                        y: constraints.maxHeight * 0.18596059113300492,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWidget1489(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.868421052631579;

                  final double height =
                      constraints.maxHeight * 0.21921182266009853;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06578947368421052,
                        y: constraints.maxHeight * 0.4421182266009852,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWidget1495(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.17980295566502463;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle364Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8223684210526315;

                  final double height =
                      constraints.maxHeight * 0.050492610837438424;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.10526315789473684,
                        y: constraints.maxHeight * 0.11699507389162561,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedWidget1501(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
