import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget587/generated/GeneratedWidget590.dart';
import 'package:flutterapp/get_startapp/generatedwidget587/generated/GeneratedWidget588.dart';

/* Frame 搜尋
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget587 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
            ),
            Positioned(
              left: 1.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 142.0,
              child: GeneratedWidget588(),
            ),
            Positioned(
              left: 0.0,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget590(),
            )
          ]),
    ));
  }
}
