import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget423/generated/GeneratedWidget424.dart';
import 'package:flutterapp/get_startapp/generatedwidget423/generated/GeneratedWidget425.dart';
import 'package:flutterapp/get_startapp/generatedwidget423/generated/GeneratedWidget426.dart';
import 'package:flutterapp/get_startapp/generatedwidget423/generated/GeneratedWidget428.dart';

/* Frame 設定-語言-通知關
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget423 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 139.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 44.0,
                      child: GeneratedWidget424(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 183.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 44.0,
                      child: GeneratedWidget425(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 139.0,
              child: GeneratedWidget426(),
            ),
            Positioned(
              left: 0.0,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget428(),
            )
          ]),
    ));
  }
}
