import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget31/generated/GeneratedLeftTitleRightWidget2.dart';
import 'package:flutterapp/get_startapp/generatedwidget31/generated/GeneratedIPhoneXornewerWidget2.dart';
import 'package:flutterapp/get_startapp/generatedwidget31/generated/GeneratedLargeTitleWidget2.dart';

/* Component 標題狀態欄
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget31 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 139.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 21.0,
              top: 88.0,
              right: 9.0,
              bottom: null,
              width: null,
              height: 43.0,
              child: GeneratedLargeTitleWidget2(),
            ),
            Positioned(
              left: 0.0,
              top: 45.0,
              right: 0.0,
              bottom: null,
              width: null,
              height: 42.0,
              child: GeneratedLeftTitleRightWidget2(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: null,
              width: null,
              height: 44.0,
              child: GeneratedIPhoneXornewerWidget2(),
            )
          ]),
    ));
  }
}
