import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget7/generated/GeneratedIPhoneXornewerWidget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget7/generated/GeneratedLargeTitleWidget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget7/generated/GeneratedLeftTitleRightWidget1.dart';

/* Component 公佈欄標題狀態欄
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 225.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 41, 41, 41),
              ),
            ),
            Positioned(
              left: 20.0,
              top: 135.0,
              right: 7.0,
              bottom: null,
              width: null,
              height: 46.0,
              child: GeneratedLargeTitleWidget1(),
            ),
            Positioned(
              left: 0.0,
              top: 45.0,
              right: 0.0,
              bottom: null,
              width: null,
              height: 42.0,
              child: GeneratedLeftTitleRightWidget1(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: null,
              width: null,
              height: 44.0,
              child: GeneratedIPhoneXornewerWidget1(),
            )
          ]),
    ));
  }
}
