import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget19/generated/GeneratedWidget29.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/get_startapp/generatedwidget19/generated/GeneratedWidget25.dart';
import 'package:flutterapp/get_startapp/generatedwidget19/generated/GeneratedDarkModeFalseWidget.dart';
import 'package:flutterapp/get_startapp/generatedwidget19/generated/GeneratedWidget28.dart';
import 'package:flutterapp/get_startapp/generatedwidget19/generated/GeneratedWidget27.dart';
import 'package:flutterapp/get_startapp/generatedwidget19/generated/GeneratedWidget26.dart';

/* Component 選單
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget19 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 82.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedDarkModeFalseWidget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.07466666666666667;

                final double height =
                    constraints.maxHeight * 0.35365853658536583;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.8693333333333333,
                      y: constraints.maxHeight * 0.036585365853658534,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget25(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.08533333333333333;

                final double height =
                    constraints.maxHeight * 0.35365853658536583;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.064,
                      y: constraints.maxHeight * 0.036585365853658534,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget26(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.07466666666666667;

                final double height =
                    constraints.maxHeight * 0.35365853658536583;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.6693333333333333,
                      y: constraints.maxHeight * 0.036585365853658534,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget27(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.09066666666666667;

                final double height =
                    constraints.maxHeight * 0.35365853658536583;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.4613333333333333,
                      y: constraints.maxHeight * 0.036585365853658534,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget28(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.07733333333333334;

                final double height =
                    constraints.maxHeight * 0.35365853658536583;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.26666666666666666,
                      y: constraints.maxHeight * 0.036585365853658534,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget29(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
