import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget46/generated/GeneratedLabelNegateActionLeftWidget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget46/generated/GeneratedBottomDividersWidget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget46/generated/GeneratedLabelNegateActionCenterWidget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget46/generated/GeneratedLabelLinkWidget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget46/generated/GeneratedLabelDisabledWidget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget46/generated/GeneratedBottomDescriptionWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/get_startapp/generatedwidget46/generated/GeneratedRightOptionsDisclosureSwitchLabelWidget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget46/generated/GeneratedWidget47.dart';
import 'package:flutterapp/get_startapp/generatedwidget46/generated/GeneratedWidget50.dart';
import 'package:flutterapp/get_startapp/generatedwidget46/generated/GeneratedLabelTitleWidget2.dart';
import 'package:flutterapp/get_startapp/generatedwidget46/generated/GeneratedTopDividersWidget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget46/generated/GeneratedWidget51.dart';
import 'package:flutterapp/get_startapp/generatedwidget46/generated/GeneratedTopHeaderWidget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget46/generated/GeneratedRemoveWidget2.dart';

/* Component 公布-標題/最新
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget46 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 88.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: 0.0,
              bottom: -0.000032783540518721566,
              width: null,
              height: 0.000032783540518721566,
              child: GeneratedBottomDividersWidget1(),
            ),
            Positioned(
              left: 0.0,
              top: 0.5,
              right: null,
              bottom: null,
              width: 375.0,
              height: 0.00003269611988798715,
              child: GeneratedTopDividersWidget1(),
            ),
            Positioned(
              left: 14.0,
              top: 11.0,
              right: null,
              bottom: null,
              width: 104.0,
              height: 27.0,
              child: GeneratedLabelTitleWidget2(),
            ),
            Positioned(
              left: 16.0,
              top: null,
              right: null,
              bottom: null,
              width: 39.0,
              height: 27.0,
              child: TransformHelper.translate(
                  x: 0.00,
                  y: 2.50,
                  z: 0,
                  child: GeneratedLabelDisabledWidget1()),
            ),
            Positioned(
              left: 16.0,
              top: null,
              right: null,
              bottom: null,
              width: 39.0,
              height: 27.0,
              child: TransformHelper.translate(
                  x: 0.00, y: 2.50, z: 0, child: GeneratedLabelLinkWidget1()),
            ),
            Positioned(
              left: 16.0,
              top: null,
              right: null,
              bottom: null,
              width: 64.0,
              height: 22.0,
              child: GeneratedRemoveWidget2(),
            ),
            Positioned(
              left: 16.0,
              top: null,
              right: null,
              bottom: null,
              width: 39.0,
              height: 27.0,
              child: TransformHelper.translate(
                  x: 0.00,
                  y: 2.50,
                  z: 0,
                  child: GeneratedLabelNegateActionLeftWidget1()),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 39.0,
              height: 27.0,
              child: TransformHelper.translate(
                  x: 3.00,
                  y: 2.50,
                  z: 0,
                  child: GeneratedLabelNegateActionCenterWidget1()),
            ),
            Positioned(
              left: 299.0,
              top: 17.5,
              right: null,
              bottom: null,
              width: 60.0,
              height: 41.5,
              child: GeneratedRightOptionsDisclosureSwitchLabelWidget1(),
            ),
            Positioned(
              left: 12.0,
              top: 52.0,
              right: 13.0,
              bottom: null,
              width: null,
              height: 15.0,
              child: GeneratedBottomDescriptionWidget1(),
            ),
            Positioned(
              left: 12.0,
              top: -26.0,
              right: 13.0,
              bottom: null,
              width: null,
              height: 18.0,
              child: GeneratedTopHeaderWidget1(),
            ),
            Positioned(
              left: 116.0,
              top: 11.0,
              right: null,
              bottom: null,
              width: 38.400001525878906,
              height: 22.0,
              child: GeneratedWidget47(),
            ),
            Positioned(
              left: 163.0,
              top: 12.0,
              right: null,
              bottom: null,
              width: 210.0,
              height: 27.0,
              child: GeneratedWidget50(),
            ),
            Positioned(
              left: 116.0,
              top: 50.0,
              right: null,
              bottom: null,
              width: 257.0,
              height: 27.0,
              child: GeneratedWidget51(),
            )
          ]),
    ));
  }
}
