import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedp1widget/generated/GeneratedWidget379.dart';
import 'package:flutterapp/get_startapp/generatedp1widget/generated/GeneratedWidget367.dart';
import 'package:flutterapp/get_startapp/generatedp1widget/generated/GeneratedWidget343.dart';
import 'package:flutterapp/get_startapp/generatedp1widget/generated/GeneratedWidget385.dart';
import 'package:flutterapp/get_startapp/generatedp1widget/generated/GeneratedWidget373.dart';
import 'package:flutterapp/get_startapp/generatedp1widget/generated/GeneratedWidget391.dart';
import 'package:flutterapp/get_startapp/generatedp1widget/generated/GeneratedWidget394.dart';
import 'package:flutterapp/get_startapp/generatedp1widget/generated/GeneratedWidget358.dart';
import 'package:flutterapp/get_startapp/generatedp1widget/generated/GeneratedWidget349.dart';
import 'package:flutterapp/get_startapp/generatedp1widget/generated/GeneratedWidget334.dart';
import 'package:flutterapp/get_startapp/generatedp1widget/generated/GeneratedWidget405.dart';

/* Frame 公布欄-P1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedP1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1032.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 1032.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 228.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 88.0,
                                    child: GeneratedWidget334(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 140.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 88.0,
                                    child: GeneratedWidget343(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 316.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 88.0,
                                    child: GeneratedWidget349(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 404.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 88.0,
                                    child: GeneratedWidget358(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 580.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 88.0,
                                    child: GeneratedWidget367(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 492.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 88.0,
                                    child: GeneratedWidget373(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 668.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 88.0,
                                    child: GeneratedWidget379(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 756.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 88.0,
                                    child: GeneratedWidget385(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 844.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 88.0,
                                    child: GeneratedWidget391(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: -2.2737367544323206e-13,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget394(),
            ),
            Positioned(
              left: null,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 139.0,
              child: GeneratedWidget405(),
            )
          ]),
    ));
  }
}
