import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget1487/generated/Generated118Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget1487/generated/Generated112Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget1487/generated/Generated120Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget1487/generated/Generated115Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget1487/generated/Generated117Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget1487/generated/Generated110Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget1487/generated/Generated111Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget1487/generated/Generated114Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget1487/generated/Generated113Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget1487/generated/Generated119Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget1487/generated/Generated109Widget9.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/get_startapp/generatedwidget1487/generated/Generated116Widget.dart';

/* Frame 年份下拉式選單
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget1487 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.only(
        topLeft: Radius.circular(0.0),
        topRight: Radius.circular(0.0),
        bottomRight: Radius.circular(20.0),
        bottomLeft: Radius.circular(20.0),
      ),
      child: Container(
        width: 81.0,
        height: 499.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(0.0),
            topRight: Radius.circular(0.0),
            bottomRight: Radius.circular(20.0),
            bottomLeft: Radius.circular(20.0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(0.0),
                  topRight: Radius.circular(0.0),
                  bottomRight: Radius.circular(20.0),
                  bottomLeft: Radius.circular(20.0),
                ),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8148148148148148;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12345679012345678,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated109Widget9(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8148148148148148;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12345679012345678,
                        y: constraints.maxHeight * 0.0841683366733467,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated110Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8148148148148148;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12345679012345678,
                        y: constraints.maxHeight * 0.1683366733466934,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated111Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8148148148148148;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12345679012345678,
                        y: constraints.maxHeight * 0.25250501002004005,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated112Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8148148148148148;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12345679012345678,
                        y: constraints.maxHeight * 0.3366733466933868,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated113Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8148148148148148;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12345679012345678,
                        y: constraints.maxHeight * 0.42084168336673344,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated114Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 66.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: 2.50, y: 16.00, z: 0, child: Generated115Widget()),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8148148148148148;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12345679012345678,
                        y: constraints.maxHeight * 0.5891783567134269,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated116Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8148148148148148;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12345679012345678,
                        y: constraints.maxHeight * 0.6733466933867736,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated117Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8148148148148148;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12345679012345678,
                        y: constraints.maxHeight * 0.7575150300601202,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated118Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8148148148148148;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12345679012345678,
                        y: constraints.maxHeight * 0.8416833667334669,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated119Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8148148148148148;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.12345679012345678,
                        y: constraints.maxHeight * 0.9258517034068137,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated120Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
