import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generated2widget6/generated/Generated820Widget1.dart';
import 'package:flutterapp/get_startapp/generated2widget6/generated/Generated1220Widget1.dart';
import 'package:flutterapp/get_startapp/generated2widget6/generated/GeneratedWidget1565.dart';
import 'package:flutterapp/get_startapp/generated2widget6/generated/GeneratedWidget1562.dart';
import 'package:flutterapp/get_startapp/generated2widget6/generated/GeneratedWidget1564.dart';

/* Frame 校園快訊2
    Autogenerated by FlutLab FTF Generator
  */
class Generated2Widget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 175.0,
                      child: GeneratedWidget1562(),
                    ),
                    Positioned(
                      left: 43.0,
                      top: 205.0,
                      right: null,
                      bottom: null,
                      width: 294.0,
                      height: 297.0,
                      child: Generated1220Widget1(),
                    ),
                    Positioned(
                      left: 209.0,
                      top: 508.0,
                      right: null,
                      bottom: null,
                      width: 127.0,
                      height: 46.0,
                      child: GeneratedWidget1564(),
                    ),
                    Positioned(
                      left: 209.0,
                      top: 549.0,
                      right: null,
                      bottom: null,
                      width: 108.0,
                      height: 46.0,
                      child: Generated820Widget1(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget1565(),
            )
          ]),
    ));
  }
}
