import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget583/generated/GeneratedTitleWidget30.dart';
import 'package:flutterapp/get_startapp/generatedwidget583/generated/GeneratedLinkWidget2.dart';
import 'package:flutterapp/get_startapp/generatedwidget583/generated/GeneratedRowlightsmalltextfielddefaultWidget4.dart';
import 'package:flutterapp/get_startapp/generatedwidget583/generated/GeneratedTitleWidget29.dart';
import 'package:flutterapp/get_startapp/generatedwidget583/generated/Generated220pxTaichung_Municipal_Taichung_First_Senior_High_Scho3.dart';
import 'package:flutterapp/get_startapp/generatedwidget583/generated/GeneratedButtonWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/get_startapp/generatedwidget583/generated/GeneratedRowlightsmalltextfielddefaultWidget5.dart';
import 'package:flutterapp/get_startapp/generatedwidget583/generated/GeneratedSystemlighthomeindicatorWidget.dart';
import 'package:flutterapp/get_startapp/generatedwidget583/generated/GeneratedSystemlightstatusbardefaultWidget2.dart';

/* Frame 登入-開始
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget583 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 171.0,
                      right: 11.0,
                      bottom: null,
                      width: null,
                      height: 46.0,
                      child: GeneratedTitleWidget29(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: 228.0,
                      right: 14.0,
                      bottom: null,
                      width: null,
                      height: 46.0,
                      child: GeneratedTitleWidget30(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 312.0,
                      right: 0.0,
                      bottom: null,
                      width: null,
                      height: 60.0,
                      child: GeneratedRowlightsmalltextfielddefaultWidget4(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 372.0,
                      right: 0.0,
                      bottom: null,
                      width: null,
                      height: 60.0,
                      child: GeneratedRowlightsmalltextfielddefaultWidget5(),
                    ),
                    Positioned(
                      left: null,
                      top: 394.0,
                      right: 11.0,
                      bottom: null,
                      width: 57.0,
                      height: 23.0,
                      child: GeneratedLinkWidget2(),
                    ),
                    Positioned(
                      left: 16.0,
                      top: null,
                      right: 16.0,
                      bottom: 118.0,
                      width: null,
                      height: 56.0,
                      child: GeneratedButtonWidget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth * 0.12;

                        final double height =
                            constraints.maxHeight * 0.054187192118226604;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.44,
                              y: constraints.maxHeight * 0.11822660098522167,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child:
                                    Generated220pxTaichung_Municipal_Taichung_First_Senior_High_Scho3(),
                              ))
                        ]);
                      }),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: 34.0,
              child: GeneratedSystemlighthomeindicatorWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: null,
              width: null,
              height: 44.0,
              child: GeneratedSystemlightstatusbardefaultWidget2(),
            )
          ]),
    ));
  }
}
