import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget1194/generated/Generated2Widget4.dart';
import 'package:flutterapp/get_startapp/generatedwidget1194/generated/GeneratedRectangle241Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget1194/generated/GeneratedCode1281Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget1194/generated/GeneratedWidget1195.dart';

/* Frame 條碼
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget1194 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedWidget1167'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Container(
                width: 375.0,
                height: 812.0,
                child: Stack(
                    fit: StackFit.expand,
                    alignment: Alignment.center,
                    overflow: Overflow.visible,
                    children: [
                      ClipRRect(
                        borderRadius: BorderRadius.zero,
                        child: Container(
                          color: Color.fromARGB(255, 255, 255, 255),
                        ),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: null,
                        bottom: null,
                        width: 375.0,
                        height: 812.0,
                        child: Generated2Widget4(),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: null,
                        bottom: null,
                        width: 375.0,
                        height: 812.0,
                        child: GeneratedRectangle241Widget(),
                      ),
                      Positioned(
                        left: 38.0,
                        top: 331.0,
                        right: null,
                        bottom: null,
                        width: 300.0,
                        height: 150.0,
                        child: GeneratedCode1281Widget(),
                      )
                    ]),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedWidget1195(),
              )
            ]),
      ),
    ));
  }
}
