import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget1963/generated/GeneratedWidget1964.dart';
import 'package:flutterapp/get_startapp/generatedwidget1963/generated/GeneratedWidget1979.dart';
import 'package:flutterapp/get_startapp/generatedwidget1963/generated/GeneratedWidget1973.dart';
import 'package:flutterapp/get_startapp/generatedwidget1963/generated/GeneratedWidget1967.dart';
import 'package:flutterapp/get_startapp/generatedwidget1963/generated/GeneratedWidget1970.dart';
import 'package:flutterapp/get_startapp/generatedwidget1963/generated/GeneratedWidget1980.dart';
import 'package:flutterapp/get_startapp/generatedwidget1963/generated/GeneratedWidget1976.dart';

/* Frame 預約/選課
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget1963 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
            ),
            Positioned(
              left: 20.0,
              top: 545.0,
              right: null,
              bottom: null,
              width: 164.0,
              height: 96.0,
              child: GeneratedWidget1964(),
            ),
            Positioned(
              left: 194.0,
              top: 545.0,
              right: null,
              bottom: null,
              width: 164.0,
              height: 96.0,
              child: GeneratedWidget1967(),
            ),
            Positioned(
              left: 194.0,
              top: 417.0,
              right: null,
              bottom: null,
              width: 164.0,
              height: 96.0,
              child: GeneratedWidget1970(),
            ),
            Positioned(
              left: 20.0,
              top: 417.0,
              right: null,
              bottom: null,
              width: 164.0,
              height: 96.0,
              child: GeneratedWidget1973(),
            ),
            Positioned(
              left: 24.0,
              top: 111.0,
              right: null,
              bottom: null,
              width: 335.0,
              height: 262.0,
              child: GeneratedWidget1976(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedWidget1979(),
            ),
            Positioned(
              left: 0.0,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget1980(),
            )
          ]),
    ));
  }
}
