import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget1485/generated/Generated12Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget1485/generated/Generated3Widget4.dart';
import 'package:flutterapp/get_startapp/generatedwidget1485/generated/Generated11Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget1485/generated/Generated1Widget48.dart';
import 'package:flutterapp/get_startapp/generatedwidget1485/generated/Generated6Widget3.dart';
import 'package:flutterapp/get_startapp/generatedwidget1485/generated/Generated9Widget2.dart';
import 'package:flutterapp/get_startapp/generatedwidget1485/generated/Generated8Widget2.dart';
import 'package:flutterapp/get_startapp/generatedwidget1485/generated/Generated4Widget4.dart';
import 'package:flutterapp/get_startapp/generatedwidget1485/generated/Generated10Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget1485/generated/Generated5Widget4.dart';
import 'package:flutterapp/get_startapp/generatedwidget1485/generated/Generated2Widget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/get_startapp/generatedwidget1485/generated/Generated7Widget2.dart';

/* Frame 月份下拉式選單
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget1485 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.only(
        topLeft: Radius.circular(0.0),
        topRight: Radius.circular(0.0),
        bottomRight: Radius.circular(20.0),
        bottomLeft: Radius.circular(20.0),
      ),
      child: Container(
        width: 68.0,
        height: 499.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(0.0),
            topRight: Radius.circular(0.0),
            bottomRight: Radius.circular(20.0),
            bottomLeft: Radius.circular(20.0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(0.0),
                  topRight: Radius.circular(0.0),
                  bottomRight: Radius.circular(20.0),
                  bottomLeft: Radius.circular(20.0),
                ),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5882352941176471;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2426470588235294,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated1Widget48(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5882352941176471;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2426470588235294,
                        y: constraints.maxHeight * 0.0841683366733467,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated2Widget5(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5882352941176471;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2426470588235294,
                        y: constraints.maxHeight * 0.1683366733466934,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated3Widget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5882352941176471;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2426470588235294,
                        y: constraints.maxHeight * 0.25250501002004005,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated4Widget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5882352941176471;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2426470588235294,
                        y: constraints.maxHeight * 0.3366733466933868,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated5Widget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5882352941176471;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2426470588235294,
                        y: constraints.maxHeight * 0.42084168336673344,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated6Widget3(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 40.0,
                height: 27.0,
                child: TransformHelper.translate(
                    x: 2.50, y: 16.00, z: 0, child: Generated7Widget2()),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5882352941176471;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2426470588235294,
                        y: constraints.maxHeight * 0.5891783567134269,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated8Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5882352941176471;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2426470588235294,
                        y: constraints.maxHeight * 0.6733466933867736,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated9Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7794117647058824;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14705882352941177,
                        y: constraints.maxHeight * 0.7575150300601202,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated10Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7794117647058824;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14705882352941177,
                        y: constraints.maxHeight * 0.8416833667334669,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated11Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7794117647058824;

                  final double height =
                      constraints.maxHeight * 0.05410821643286573;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.14705882352941177,
                        y: constraints.maxHeight * 0.9258517034068137,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated12Widget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
