import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedtestwidget/generated/GeneratedWidget548.dart';
import 'package:flutterapp/get_startapp/generatedtestwidget/generated/GeneratedWidget558.dart';
import 'package:flutterapp/get_startapp/generatedtestwidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/get_startapp/generatedtestwidget/generated/GeneratedWidget564.dart';
import 'package:flutterapp/get_startapp/generatedtestwidget/generated/GeneratedUnionWidget3.dart';
import 'package:flutterapp/get_startapp/generatedtestwidget/generated/GeneratedWidget568.dart';
import 'package:flutterapp/get_startapp/generatedtestwidget/generated/GeneratedWidget562.dart';
import 'package:flutterapp/get_startapp/generatedtestwidget/generated/GeneratedWidget566.dart';
import 'package:flutterapp/get_startapp/generatedtestwidget/generated/GeneratedWidget560.dart';
import 'package:flutterapp/get_startapp/generatedtestwidget/generated/GeneratedGroup7Widget.dart';

/* Frame 缺曠/請假-主頁test
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedtestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 53.0,
                      top: 146.0,
                      right: null,
                      bottom: null,
                      width: 161.0,
                      height: 22.0,
                      child: GeneratedGroup4Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 261.0,
                      right: null,
                      bottom: null,
                      width: 86.0,
                      height: 148.0,
                      child: GeneratedWidget548(),
                    ),
                    Positioned(
                      left: 86.0,
                      top: 201.0,
                      right: null,
                      bottom: null,
                      width: 284.0,
                      height: 24.0,
                      child: GeneratedGroup7Widget(),
                    ),
                    Positioned(
                      left: 111.0,
                      top: 201.0,
                      right: null,
                      bottom: null,
                      width: 234.0,
                      height: 498.0,
                      child: GeneratedUnionWidget3(),
                    ),
                    Positioned(
                      left: 81.0,
                      top: 257.0,
                      right: null,
                      bottom: null,
                      width: 30.0,
                      height: 30.0,
                      child: GeneratedWidget558(),
                    ),
                    Positioned(
                      left: 114.0,
                      top: 257.0,
                      right: null,
                      bottom: null,
                      width: 30.0,
                      height: 30.0,
                      child: GeneratedWidget560(),
                    ),
                    Positioned(
                      left: 180.0,
                      top: 257.0,
                      right: null,
                      bottom: null,
                      width: 30.0,
                      height: 30.0,
                      child: GeneratedWidget562(),
                    ),
                    Positioned(
                      left: 147.0,
                      top: 257.0,
                      right: null,
                      bottom: null,
                      width: 30.0,
                      height: 30.0,
                      child: GeneratedWidget564(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 139.0,
              child: GeneratedWidget566(),
            ),
            Positioned(
              left: 0.0,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget568(),
            )
          ]),
    ));
  }
}
