import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget1146/generated/GeneratedWidget1151.dart';
import 'package:flutterapp/get_startapp/generatedwidget1146/generated/GeneratedPageHeaderWidget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget1146/generated/GeneratedWidget1153.dart';
import 'package:flutterapp/get_startapp/generatedwidget1146/generated/GeneratedWidget1149.dart';
import 'package:flutterapp/get_startapp/generatedwidget1146/generated/GeneratedWidget1154.dart';
import 'package:flutterapp/get_startapp/generatedwidget1146/generated/GeneratedIOSStatusBarWhiteWidget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget1146/generated/GeneratedNameBioWidget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget1146/generated/GeneratedWidget1150.dart';
import 'package:flutterapp/get_startapp/generatedwidget1146/generated/GeneratedEllipse6Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget1146/generated/GeneratedRectangle239Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/get_startapp/generatedwidget1146/generated/GeneratedWidget1147.dart';
import 'package:flutterapp/get_startapp/generatedwidget1146/generated/GeneratedWidget1152.dart';

/* Frame 設定-主頁-通知關
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget1146 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 44.0,
                      child: GeneratedWidget1147(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: null,
                      width: null,
                      height: 245.0,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth - -1.0;
                        final double scaleX = width <= 0 ? 0 : (width / 376.0);

                        final Widget child = GeneratedRectangle239Widget1();
                        return Stack(children: [
                          Transform(
                            transform: Matrix4(scaleX, 0, 0, 0, 0, 1, 0, 0, 0,
                                0, 1, 0, 0.0, 0.0, 0, 1),
                            alignment: Alignment.topLeft,
                            child: SizedBox.expand(child: child),
                          )
                        ]);
                      }),
                    ),
                    Positioned(
                      left: null,
                      top: 128.0,
                      right: null,
                      bottom: null,
                      width: 158.0,
                      height: 158.0,
                      child: TransformHelper.translate(
                          x: -0.50,
                          y: 0.00,
                          z: 0,
                          child: GeneratedEllipse6Widget1()),
                    )
                  ]),
            ),
            Positioned(
              left: 156.0,
              top: 302.0,
              right: null,
              bottom: null,
              width: 65.0,
              height: 63.0,
              child: GeneratedNameBioWidget1(),
            ),
            Positioned(
              left: 17.0,
              top: 397.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 36.0,
              child: GeneratedWidget1149(),
            ),
            Positioned(
              left: 0.0,
              top: 581.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedWidget1150(),
            ),
            Positioned(
              left: 0.0,
              top: 493.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedWidget1151(),
            ),
            Positioned(
              left: 0.0,
              top: 537.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedWidget1152(),
            ),
            Positioned(
              left: 0.0,
              top: 449.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedWidget1153(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: null,
              width: null,
              height: 44.0,
              child: GeneratedIOSStatusBarWhiteWidget1(),
            ),
            Positioned(
              left: 0.0,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget1154(),
            ),
            Positioned(
              left: 16.0,
              top: 60.0,
              right: 16.0,
              bottom: null,
              width: null,
              height: 36.0,
              child: GeneratedPageHeaderWidget1(),
            )
          ]),
    ));
  }
}
