import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget2734/generated/GeneratedKeysWidget7.dart';
import 'package:flutterapp/get_startapp/generatedwidget2734/generated/GeneratedHomeIndicatorWidget146.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Instance 英文鍵盤
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget2734 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 291.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 209, 213, 219),
              ),
            ),
            Positioned(
              left: 1.0,
              top: null,
              right: -1.0,
              bottom: 0.0,
              width: null,
              height: 34.0,
              child: GeneratedHomeIndicatorWidget146(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.984;

                final double height =
                    constraints.maxHeight * 0.8900343642611683;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.008,
                      y: constraints.maxHeight * 0.027491408934707903,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedKeysWidget7(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
