import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget1947/generated/GeneratedButtonWidget3.dart';
import 'package:flutterapp/get_startapp/generatedwidget1947/generated/GeneratedLinkWidget7.dart';
import 'package:flutterapp/get_startapp/generatedwidget1947/generated/GeneratedTitleWidget66.dart';
import 'package:flutterapp/get_startapp/generatedwidget1947/generated/Generated220pxTaichung_Municipal_Taichung_First_Senior_High_Scho9.dart';
import 'package:flutterapp/get_startapp/generatedwidget1947/generated/GeneratedSystemlightstatusbardefaultWidget7.dart';
import 'package:flutterapp/get_startapp/generatedwidget1947/generated/GeneratedRowlightsmalltextfielddefaultWidget15.dart';
import 'package:flutterapp/get_startapp/generatedwidget1947/generated/GeneratedRowlightsmalltextfielddefaultWidget14.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/get_startapp/generatedwidget1947/generated/GeneratedTitleWidget67.dart';
import 'package:flutterapp/get_startapp/generatedwidget1947/generated/GeneratedSystemlighthomeindicatorWidget3.dart';

/* Frame 登入-完成
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget1947 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedSystemlightstatusbardefaultWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: 34.0,
                child: GeneratedSystemlighthomeindicatorWidget3(),
              ),
              Positioned(
                left: 16.0,
                top: 228.0,
                right: 14.0,
                bottom: null,
                width: null,
                height: 46.0,
                child: GeneratedTitleWidget66(),
              ),
              Positioned(
                left: 0.0,
                top: 312.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 60.0,
                child: GeneratedRowlightsmalltextfielddefaultWidget14(),
              ),
              Positioned(
                left: 0.0,
                top: 372.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 60.0,
                child: GeneratedRowlightsmalltextfielddefaultWidget15(),
              ),
              Positioned(
                left: null,
                top: 394.0,
                right: 11.0,
                bottom: null,
                width: 57.0,
                height: 23.0,
                child: GeneratedLinkWidget7(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 118.0,
                width: null,
                height: 56.0,
                child: GeneratedButtonWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.12;

                  final double height =
                      constraints.maxHeight * 0.054187192118226604;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.44,
                        y: constraints.maxHeight * 0.11822660098522167,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              Generated220pxTaichung_Municipal_Taichung_First_Senior_High_Scho9(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 16.0,
                top: 171.0,
                right: 11.0,
                bottom: null,
                width: null,
                height: 46.0,
                child: GeneratedTitleWidget67(),
              )
            ]),
      ),
    ));
  }
}
