import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget1479/generated/GeneratedWidget1480.dart';
import 'package:flutterapp/get_startapp/generatedwidget1479/generated/GeneratedWidget1481.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/get_startapp/generatedwidget1479/generated/GeneratedRectangle319Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget1479/generated/GeneratedWidget1482.dart';
import 'package:flutterapp/get_startapp/generatedwidget1479/generated/GeneratedWidget1483.dart';

/* Instance 行事曆詳細
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget1479 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 350.0,
      height: 200.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget1480(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.74;

                final double height = constraints.maxHeight * 0.135;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.13428580147879465,
                      y: constraints.maxHeight * 0.18,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget1481(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9;

                final double height = constraints.maxHeight * 0.12;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05089820316859654,
                      y: constraints.maxHeight * 0.525,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget1482(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.3514285714285714;

                final double height = constraints.maxHeight * 0.135;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05089820316859654,
                      y: constraints.maxHeight * 0.725,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget1483(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.8083832659040179;

                final double height = constraints.maxHeight * 0.015;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.09714279174804688,
                      y: constraints.maxHeight * 0.39,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle319Widget1(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
