import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget89/generated/Generated109Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget89/generated/GeneratedWidget90.dart';
import 'package:flutterapp/get_startapp/generatedwidget89/generated/GeneratedWidget91.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/get_startapp/generatedwidget89/generated/GeneratedWidget93.dart';
import 'package:flutterapp/get_startapp/generatedwidget89/generated/GeneratedWidget94.dart';
import 'package:flutterapp/get_startapp/generatedwidget89/generated/GeneratedWidget92.dart';
import 'package:flutterapp/get_startapp/generatedwidget89/generated/GeneratedRectangle318Widget.dart';

/* Component 成績查詢
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget89 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 132.0,
      height: 178.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height =
                    constraints.maxHeight * 0.16853932584269662;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle318Widget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9696969696969697;

                final double height =
                    constraints.maxHeight * 0.15168539325842698;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.030303030303030304,
                      y: constraints.maxHeight * 0.028089887640449437,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated109Widget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.8712121212121212;

                final double height =
                    constraints.maxHeight * 0.15168539325842698;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.09090909090909091,
                      y: constraints.maxHeight * 0.2247191011235955,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget90(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.8712121212121212;

                final double height =
                    constraints.maxHeight * 0.15168539325842698;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.09090909090909091,
                      y: constraints.maxHeight * 0.38764044943820225,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget91(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.8712121212121212;

                final double height =
                    constraints.maxHeight * 0.15168539325842698;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.09090909090909091,
                      y: constraints.maxHeight * 0.550561797752809,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget92(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.5151515151515151;

                final double height =
                    constraints.maxHeight * 0.15168539325842698;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.2727272727272727,
                      y: constraints.maxHeight * 0.7134831460674157,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget93(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.5151515151515151;

                final double height =
                    constraints.maxHeight * 0.15168539325842698;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.2727272727272727,
                      y: constraints.maxHeight * 0.8764044943820225,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget94(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
