import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget61/generated/GeneratedBottomDividersWidget4.dart';
import 'package:flutterapp/get_startapp/generatedwidget61/generated/GeneratedTopDividersWidget4.dart';
import 'package:flutterapp/get_startapp/generatedwidget61/generated/GeneratedLabelNegateActionCenterWidget4.dart';
import 'package:flutterapp/get_startapp/generatedwidget61/generated/GeneratedLabelTitleWidget8.dart';
import 'package:flutterapp/get_startapp/generatedwidget61/generated/GeneratedLabelDisabledWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/get_startapp/generatedwidget61/generated/GeneratedRemoveWidget8.dart';
import 'package:flutterapp/get_startapp/generatedwidget61/generated/GeneratedLabelLinkWidget4.dart';
import 'package:flutterapp/get_startapp/generatedwidget61/generated/GeneratedBottomDescriptionWidget4.dart';
import 'package:flutterapp/get_startapp/generatedwidget61/generated/GeneratedLabelNegateActionLeftWidget4.dart';
import 'package:flutterapp/get_startapp/generatedwidget61/generated/GeneratedRightOptionsDisclosureSwitchLabelWidget4.dart';
import 'package:flutterapp/get_startapp/generatedwidget61/generated/GeneratedTopHeaderWidget4.dart';

/* Component 設定/文字
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget61 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 44.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: 0.0,
              bottom: -0.000032783540518721566,
              width: null,
              height: 0.000032783540518721566,
              child: GeneratedBottomDividersWidget4(),
            ),
            Positioned(
              left: 0.0,
              top: 0.5,
              right: null,
              bottom: null,
              width: 375.0,
              height: 0.00003269611988798715,
              child: GeneratedTopDividersWidget4(),
            ),
            Positioned(
              left: 16.0,
              top: null,
              right: null,
              bottom: null,
              width: 58.0,
              height: 27.0,
              child: TransformHelper.translate(
                  x: 0.00, y: 2.50, z: 0, child: GeneratedLabelTitleWidget8()),
            ),
            Positioned(
              left: 16.0,
              top: null,
              right: null,
              bottom: null,
              width: 39.0,
              height: 27.0,
              child: TransformHelper.translate(
                  x: 0.00,
                  y: 2.50,
                  z: 0,
                  child: GeneratedLabelDisabledWidget4()),
            ),
            Positioned(
              left: 16.0,
              top: null,
              right: null,
              bottom: null,
              width: 39.0,
              height: 27.0,
              child: TransformHelper.translate(
                  x: 0.00, y: 2.50, z: 0, child: GeneratedLabelLinkWidget4()),
            ),
            Positioned(
              left: 16.0,
              top: null,
              right: null,
              bottom: null,
              width: 64.0,
              height: 22.0,
              child: GeneratedRemoveWidget8(),
            ),
            Positioned(
              left: 16.0,
              top: null,
              right: null,
              bottom: null,
              width: 39.0,
              height: 27.0,
              child: TransformHelper.translate(
                  x: 0.00,
                  y: 2.50,
                  z: 0,
                  child: GeneratedLabelNegateActionLeftWidget4()),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 39.0,
              height: 27.0,
              child: TransformHelper.translate(
                  x: 3.00,
                  y: 2.50,
                  z: 0,
                  child: GeneratedLabelNegateActionCenterWidget4()),
            ),
            Positioned(
              left: 299.0,
              top: 6.0,
              right: null,
              bottom: null,
              width: 60.0,
              height: 31.0,
              child: GeneratedRightOptionsDisclosureSwitchLabelWidget4(),
            ),
            Positioned(
              left: 12.0,
              top: 52.0,
              right: 13.0,
              bottom: null,
              width: null,
              height: 15.0,
              child: GeneratedBottomDescriptionWidget4(),
            ),
            Positioned(
              left: 12.0,
              top: -26.0,
              right: 13.0,
              bottom: null,
              width: null,
              height: 18.0,
              child: GeneratedTopHeaderWidget4(),
            )
          ]),
    ));
  }
}
