import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget37/generated/GeneratedBottomDividersWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/get_startapp/generatedwidget37/generated/GeneratedRightOptionsDisclosureSwitchLabelWidget.dart';
import 'package:flutterapp/get_startapp/generatedwidget37/generated/GeneratedWidget42.dart';
import 'package:flutterapp/get_startapp/generatedwidget37/generated/GeneratedLabelTitleWidget.dart';
import 'package:flutterapp/get_startapp/generatedwidget37/generated/GeneratedWidget39.dart';
import 'package:flutterapp/get_startapp/generatedwidget37/generated/GeneratedLabelDisabledWidget.dart';
import 'package:flutterapp/get_startapp/generatedwidget37/generated/GeneratedWidget38.dart';
import 'package:flutterapp/get_startapp/generatedwidget37/generated/GeneratedLabelLinkWidget.dart';
import 'package:flutterapp/get_startapp/generatedwidget37/generated/GeneratedLabelNegateActionCenterWidget.dart';
import 'package:flutterapp/get_startapp/generatedwidget37/generated/GeneratedTopHeaderWidget.dart';
import 'package:flutterapp/get_startapp/generatedwidget37/generated/GeneratedTopDividersWidget.dart';
import 'package:flutterapp/get_startapp/generatedwidget37/generated/GeneratedRemoveWidget.dart';
import 'package:flutterapp/get_startapp/generatedwidget37/generated/GeneratedWidget45.dart';
import 'package:flutterapp/get_startapp/generatedwidget37/generated/GeneratedBottomDescriptionWidget.dart';
import 'package:flutterapp/get_startapp/generatedwidget37/generated/GeneratedLabelNegateActionLeftWidget.dart';

/* Component 公布-標題/置頂+最新
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget37 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 88.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: null,
              right: 0.0,
              bottom: -0.000032783540518721566,
              width: null,
              height: 0.000032783540518721566,
              child: GeneratedBottomDividersWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.5,
              right: null,
              bottom: null,
              width: 375.0,
              height: 0.00003269611988798715,
              child: GeneratedTopDividersWidget(),
            ),
            Positioned(
              left: 14.0,
              top: 11.0,
              right: null,
              bottom: null,
              width: 104.0,
              height: 27.0,
              child: GeneratedLabelTitleWidget(),
            ),
            Positioned(
              left: 16.0,
              top: null,
              right: null,
              bottom: null,
              width: 39.0,
              height: 27.0,
              child: TransformHelper.translate(
                  x: 0.00,
                  y: 2.50,
                  z: 0,
                  child: GeneratedLabelDisabledWidget()),
            ),
            Positioned(
              left: 16.0,
              top: null,
              right: null,
              bottom: null,
              width: 39.0,
              height: 27.0,
              child: TransformHelper.translate(
                  x: 0.00, y: 2.50, z: 0, child: GeneratedLabelLinkWidget()),
            ),
            Positioned(
              left: 16.0,
              top: null,
              right: null,
              bottom: null,
              width: 64.0,
              height: 22.0,
              child: GeneratedRemoveWidget(),
            ),
            Positioned(
              left: 16.0,
              top: null,
              right: null,
              bottom: null,
              width: 39.0,
              height: 27.0,
              child: TransformHelper.translate(
                  x: 0.00,
                  y: 2.50,
                  z: 0,
                  child: GeneratedLabelNegateActionLeftWidget()),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 39.0,
              height: 27.0,
              child: TransformHelper.translate(
                  x: 3.00,
                  y: 2.50,
                  z: 0,
                  child: GeneratedLabelNegateActionCenterWidget()),
            ),
            Positioned(
              left: 299.0,
              top: 17.5,
              right: null,
              bottom: null,
              width: 60.0,
              height: 41.5,
              child: GeneratedRightOptionsDisclosureSwitchLabelWidget(),
            ),
            Positioned(
              left: 12.0,
              top: 52.0,
              right: 13.0,
              bottom: null,
              width: null,
              height: 15.0,
              child: GeneratedBottomDescriptionWidget(),
            ),
            Positioned(
              left: 12.0,
              top: -26.0,
              right: 13.0,
              bottom: null,
              width: null,
              height: 18.0,
              child: GeneratedTopHeaderWidget(),
            ),
            Positioned(
              left: 201.0,
              top: 12.0,
              right: null,
              bottom: null,
              width: 172.0,
              height: 27.0,
              child: GeneratedWidget38(),
            ),
            Positioned(
              left: 116.0,
              top: 11.0,
              right: null,
              bottom: null,
              width: 38.400001525878906,
              height: 22.0,
              child: GeneratedWidget39(),
            ),
            Positioned(
              left: 158.0,
              top: 11.0,
              right: null,
              bottom: null,
              width: 38.400001525878906,
              height: 22.0,
              child: GeneratedWidget42(),
            ),
            Positioned(
              left: 116.0,
              top: 50.0,
              right: null,
              bottom: null,
              width: 257.0,
              height: 27.0,
              child: GeneratedWidget45(),
            )
          ]),
    ));
  }
}
