import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedVector8Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1875.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1906.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/Generated20200230Widget28.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/Generated20200230Widget18.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1892.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedVector6Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1888.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1894.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedVector7Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1904.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1902.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1912.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/Generated20200230Widget24.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedVector2Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1914.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedVector5Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1873.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1926.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedVector1Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/Generated20200230Widget26.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedVector3Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedVector9Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1920.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1922.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/Generated20200230Widget22.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1865.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/Generated20200230Widget30.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1863.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/Generated20200230Widget20.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1908.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1896.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1867.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1898.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1877.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedVector4Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1900.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1910.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1918.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1924.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/Generated20200230Widget32.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1928.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1871.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1930.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1869.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1890.dart';
import 'package:flutterapp/get_startapp/generatedwidget1862/generated/GeneratedWidget1916.dart';

/* Frame 缺曠/請假-主頁
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget1862 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 196.0,
                      right: null,
                      bottom: null,
                      width: 71.0,
                      height: 16.0,
                      child: Generated20200230Widget18(),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 71.0,
                      height: 16.0,
                      child: Generated20200230Widget20(),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 250.0,
                      right: null,
                      bottom: null,
                      width: 71.0,
                      height: 16.0,
                      child: Generated20200230Widget22(),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 277.0,
                      right: null,
                      bottom: null,
                      width: 71.0,
                      height: 16.0,
                      child: Generated20200230Widget24(),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 304.0,
                      right: null,
                      bottom: null,
                      width: 71.0,
                      height: 16.0,
                      child: Generated20200230Widget26(),
                    ),
                    Positioned(
                      left: 224.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 0.0,
                      height: 537.0,
                      child: GeneratedVector1Widget1(),
                    ),
                    Positioned(
                      left: 249.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 0.0,
                      height: 537.0,
                      child: GeneratedVector6Widget1(),
                    ),
                    Positioned(
                      left: 274.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 0.0,
                      height: 537.0,
                      child: GeneratedVector7Widget1(),
                    ),
                    Positioned(
                      left: 299.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 0.0,
                      height: 537.0,
                      child: GeneratedVector8Widget1(),
                    ),
                    Positioned(
                      left: 324.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 0.0,
                      height: 537.0,
                      child: GeneratedVector9Widget1(),
                    ),
                    Positioned(
                      left: 149.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 0.0,
                      height: 537.0,
                      child: GeneratedVector2Widget1(),
                    ),
                    Positioned(
                      left: 124.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 0.0,
                      height: 537.0,
                      child: GeneratedVector5Widget1(),
                    ),
                    Positioned(
                      left: 199.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 0.0,
                      height: 537.0,
                      child: GeneratedVector4Widget1(),
                    ),
                    Positioned(
                      left: 174.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 0.0,
                      height: 537.0,
                      child: GeneratedVector3Widget1(),
                    ),
                    Positioned(
                      left: 106.0,
                      top: 196.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1863(),
                    ),
                    Positioned(
                      left: 131.0,
                      top: 196.0,
                      right: null,
                      bottom: null,
                      width: 12.0,
                      height: 16.0,
                      child: GeneratedWidget1865(),
                    ),
                    Positioned(
                      left: 106.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1867(),
                    ),
                    Positioned(
                      left: 206.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1869(),
                    ),
                    Positioned(
                      left: 156.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1871(),
                    ),
                    Positioned(
                      left: 181.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1873(),
                    ),
                    Positioned(
                      left: 131.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1875(),
                    ),
                    Positioned(
                      left: 106.0,
                      top: 174.0,
                      right: null,
                      bottom: null,
                      width: 239.0,
                      height: 13.0,
                      child: GeneratedWidget1877(),
                    ),
                    Positioned(
                      left: 231.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1888(),
                    ),
                    Positioned(
                      left: 256.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1890(),
                    ),
                    Positioned(
                      left: 281.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1892(),
                    ),
                    Positioned(
                      left: 306.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1894(),
                    ),
                    Positioned(
                      left: 331.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1896(),
                    ),
                    Positioned(
                      left: 231.0,
                      top: 250.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1898(),
                    ),
                    Positioned(
                      left: 206.0,
                      top: 277.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1900(),
                    ),
                    Positioned(
                      left: 281.0,
                      top: 304.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1902(),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 71.0,
                      height: 16.0,
                      child: Generated20200230Widget28(),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 358.0,
                      right: null,
                      bottom: null,
                      width: 71.0,
                      height: 16.0,
                      child: Generated20200230Widget30(),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 385.0,
                      right: null,
                      bottom: null,
                      width: 71.0,
                      height: 16.0,
                      child: Generated20200230Widget32(),
                    ),
                    Positioned(
                      left: 106.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1904(),
                    ),
                    Positioned(
                      left: 131.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1906(),
                    ),
                    Positioned(
                      left: 156.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1908(),
                    ),
                    Positioned(
                      left: 181.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1910(),
                    ),
                    Positioned(
                      left: 206.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1912(),
                    ),
                    Positioned(
                      left: 231.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1914(),
                    ),
                    Positioned(
                      left: 256.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1916(),
                    ),
                    Positioned(
                      left: 281.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1918(),
                    ),
                    Positioned(
                      left: 306.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1920(),
                    ),
                    Positioned(
                      left: 331.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1922(),
                    ),
                    Positioned(
                      left: 156.0,
                      top: 358.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1924(),
                    ),
                    Positioned(
                      left: 181.0,
                      top: 390.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget1926(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 139.0,
              child: GeneratedWidget1928(),
            ),
            Positioned(
              left: 0.0,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget1930(),
            )
          ]),
    ));
  }
}
