import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget2718/generated/Generated116Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget2718/generated/Generated113Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget2718/generated/Generated117Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget2718/generated/Generated109Widget17.dart';
import 'package:flutterapp/get_startapp/generatedwidget2718/generated/Generated111Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/get_startapp/generatedwidget2718/generated/Generated110Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget2718/generated/Generated119Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget2718/generated/Generated112Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget2718/generated/Generated114Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget2718/generated/Generated115Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget2718/generated/Generated118Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget2718/generated/Generated120Widget1.dart';

/* Instance 年份
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget2718 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 75.0,
      height: 480.0,
      decoration: BoxDecoration(
        border: Border.all(
          width: 1.2999999523162842,
          color: Color.fromARGB(255, 0, 0, 0),
        ),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated109Widget17(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.08333333333333333,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated110Widget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.16666666666666666,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated111Widget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.25,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated112Widget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.3333333333333333,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated113Widget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.4166666666666667,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated114Widget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.5,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated115Widget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.5833333333333334,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated116Widget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.6666666666666666,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated117Widget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.75,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated118Widget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.8333333333333334,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated119Widget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.9166666666666666,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated120Widget1(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
