import 'package:flutter/material.dart';

/* Rectangle EMT 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEMT1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 550.0,
      height: 550.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/5db0b477bee8747179d600e5f6e7c03ad519c1b4.png",
          color: null,
          fit: BoxFit.cover,
          width: 550.0,
          height: 550.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
