import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget2530/generated/GeneratedWidget2545.dart';
import 'package:flutterapp/get_startapp/generatedwidget2530/generated/GeneratedGroup3Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget2530/generated/GeneratedWidget2531.dart';
import 'package:flutterapp/get_startapp/generatedwidget2530/generated/GeneratedWidget2537.dart';
import 'package:flutterapp/get_startapp/generatedwidget2530/generated/GeneratedWidget2546.dart';
import 'package:flutterapp/get_startapp/generatedwidget2530/generated/GeneratedWidget2534.dart';
import 'package:flutterapp/get_startapp/generatedwidget2530/generated/GeneratedWidget2540.dart';

/* Frame 主頁
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget2530 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
            ),
            Positioned(
              left: 20.0,
              top: 545.0,
              right: null,
              bottom: null,
              width: 164.0,
              height: 96.0,
              child: GeneratedWidget2531(),
            ),
            Positioned(
              left: 194.0,
              top: 545.0,
              right: null,
              bottom: null,
              width: 164.0,
              height: 96.0,
              child: GeneratedWidget2534(),
            ),
            Positioned(
              left: 194.0,
              top: 418.0,
              right: null,
              bottom: null,
              width: 164.0,
              height: 96.0,
              child: GeneratedWidget2537(),
            ),
            Positioned(
              left: 20.0,
              top: 417.0,
              right: null,
              bottom: null,
              width: 164.0,
              height: 96.0,
              child: GeneratedWidget2540(),
            ),
            Positioned(
              left: 24.0,
              top: 131.0,
              right: null,
              bottom: null,
              width: 334.0,
              height: 200.0,
              child: GeneratedGroup3Widget1(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedWidget2545(),
            ),
            Positioned(
              left: 0.0,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget2546(),
            )
          ]),
    ));
  }
}
