import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget2486/generated/GeneratedWidget2492.dart';
import 'package:flutterapp/get_startapp/generatedwidget2486/generated/GeneratedWidget2491.dart';
import 'package:flutterapp/get_startapp/generatedwidget2486/generated/GeneratedWidget2490.dart';
import 'package:flutterapp/get_startapp/generatedwidget2486/generated/GeneratedWidget2487.dart';
import 'package:flutterapp/get_startapp/generatedwidget2486/generated/GeneratedEllipse6Widget2.dart';
import 'package:flutterapp/get_startapp/generatedwidget2486/generated/GeneratedNameBioWidget2.dart';
import 'package:flutterapp/get_startapp/generatedwidget2486/generated/GeneratedWidget2488.dart';
import 'package:flutterapp/get_startapp/generatedwidget2486/generated/GeneratedRectangle239Widget2.dart';
import 'package:flutterapp/get_startapp/generatedwidget2486/generated/GeneratedWidget2494.dart';
import 'package:flutterapp/get_startapp/generatedwidget2486/generated/GeneratedIOSStatusBarWhiteWidget2.dart';
import 'package:flutterapp/get_startapp/generatedwidget2486/generated/GeneratedWidget2489.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/get_startapp/generatedwidget2486/generated/GeneratedPageHeaderWidget2.dart';

/* Frame 設定
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget2486 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 44.0,
                      child: GeneratedWidget2487(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: null,
                      width: null,
                      height: 245.0,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth - -1.0;
                        final double scaleX = width <= 0 ? 0 : (width / 376.0);

                        final Widget child = GeneratedRectangle239Widget2();
                        return Stack(children: [
                          Transform(
                            transform: Matrix4(scaleX, 0, 0, 0, 0, 1, 0, 0, 0,
                                0, 1, 0, 0.0, 0.0, 0, 1),
                            alignment: Alignment.topLeft,
                            child: SizedBox.expand(child: child),
                          )
                        ]);
                      }),
                    ),
                    Positioned(
                      left: null,
                      top: 128.0,
                      right: null,
                      bottom: null,
                      width: 158.0,
                      height: 158.0,
                      child: TransformHelper.translate(
                          x: -0.50,
                          y: 0.00,
                          z: 0,
                          child: GeneratedEllipse6Widget2()),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 449.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedWidget2488(),
            ),
            Positioned(
              left: 0.0,
              top: 493.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedWidget2489(),
            ),
            Positioned(
              left: 0.0,
              top: 537.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedWidget2490(),
            ),
            Positioned(
              left: 0.0,
              top: 581.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedWidget2491(),
            ),
            Positioned(
              left: 17.0,
              top: 397.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 36.0,
              child: GeneratedWidget2492(),
            ),
            Positioned(
              left: 128.0,
              top: 302.0,
              right: null,
              bottom: null,
              width: 120.0,
              height: 63.0,
              child: GeneratedNameBioWidget2(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: null,
              width: null,
              height: 44.0,
              child: GeneratedIOSStatusBarWhiteWidget2(),
            ),
            Positioned(
              left: 0.0,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget2494(),
            ),
            Positioned(
              left: 16.0,
              top: 60.0,
              right: 16.0,
              bottom: null,
              width: null,
              height: 36.0,
              child: GeneratedPageHeaderWidget2(),
            )
          ]),
    ));
  }
}
