import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget2507/generated/GeneratedWidget2511.dart';
import 'package:flutterapp/get_startapp/generatedwidget2507/generated/GeneratedRectangle239Widget3.dart';
import 'package:flutterapp/get_startapp/generatedwidget2507/generated/GeneratedNameBioWidget3.dart';
import 'package:flutterapp/get_startapp/generatedwidget2507/generated/GeneratedWidget2512.dart';
import 'package:flutterapp/get_startapp/generatedwidget2507/generated/GeneratedEllipse6Widget3.dart';
import 'package:flutterapp/get_startapp/generatedwidget2507/generated/GeneratedWidget2508.dart';
import 'package:flutterapp/get_startapp/generatedwidget2507/generated/GeneratedWidget2510.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/get_startapp/generatedwidget2507/generated/GeneratedIOSStatusBarWhiteWidget3.dart';
import 'package:flutterapp/get_startapp/generatedwidget2507/generated/GeneratedWidget2517.dart';
import 'package:flutterapp/get_startapp/generatedwidget2507/generated/GeneratedWidget2509.dart';
import 'package:flutterapp/get_startapp/generatedwidget2507/generated/GeneratedPageHeaderWidget3.dart';
import 'package:flutterapp/get_startapp/generatedwidget2507/generated/GeneratedWidget2513.dart';

/* Frame 設定-主頁-通知關
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget2507 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 44.0,
                      child: GeneratedWidget2508(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: null,
                      width: null,
                      height: 245.0,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth - -1.0;
                        final double scaleX = width <= 0 ? 0 : (width / 376.0);

                        final Widget child = GeneratedRectangle239Widget3();
                        return Stack(children: [
                          Transform(
                            transform: Matrix4(scaleX, 0, 0, 0, 0, 1, 0, 0, 0,
                                0, 1, 0, 0.0, 0.0, 0, 1),
                            alignment: Alignment.topLeft,
                            child: SizedBox.expand(child: child),
                          )
                        ]);
                      }),
                    ),
                    Positioned(
                      left: null,
                      top: 128.0,
                      right: null,
                      bottom: null,
                      width: 158.0,
                      height: 158.0,
                      child: TransformHelper.translate(
                          x: -0.50,
                          y: 0.00,
                          z: 0,
                          child: GeneratedEllipse6Widget3()),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 581.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedWidget2509(),
            ),
            Positioned(
              left: 0.0,
              top: 493.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedWidget2510(),
            ),
            Positioned(
              left: 0.0,
              top: 537.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedWidget2511(),
            ),
            Positioned(
              left: 0.0,
              top: 449.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedWidget2512(),
            ),
            Positioned(
              left: 17.0,
              top: 397.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 36.0,
              child: GeneratedWidget2513(),
            ),
            Positioned(
              left: 128.0,
              top: 302.0,
              right: null,
              bottom: null,
              width: 120.0,
              height: 63.0,
              child: GeneratedNameBioWidget3(),
            ),
            Positioned(
              left: 16.0,
              top: 60.0,
              right: 16.0,
              bottom: null,
              width: null,
              height: 36.0,
              child: GeneratedPageHeaderWidget3(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: null,
              width: null,
              height: 44.0,
              child: GeneratedIOSStatusBarWhiteWidget3(),
            ),
            Positioned(
              left: 0.0,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget2517(),
            )
          ]),
    ));
  }
}
