import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget1167/generated/GeneratedWidget1180.dart';
import 'package:flutterapp/get_startapp/generatedwidget1167/generated/GeneratedWidget1171.dart';
import 'package:flutterapp/get_startapp/generatedwidget1167/generated/GeneratedWidget1183.dart';
import 'package:flutterapp/get_startapp/generatedwidget1167/generated/GeneratedWidget1182.dart';
import 'package:flutterapp/get_startapp/generatedwidget1167/generated/GeneratedWidget1174.dart';
import 'package:flutterapp/get_startapp/generatedwidget1167/generated/GeneratedWidget1168.dart';
import 'package:flutterapp/get_startapp/generatedwidget1167/generated/GeneratedWidget1177.dart';

/* Frame 主頁
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget1167 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
            ),
            Positioned(
              left: 20.0,
              top: 545.0,
              right: null,
              bottom: null,
              width: 164.0,
              height: 96.0,
              child: GeneratedWidget1168(),
            ),
            Positioned(
              left: 194.0,
              top: 545.0,
              right: null,
              bottom: null,
              width: 164.0,
              height: 96.0,
              child: GeneratedWidget1171(),
            ),
            Positioned(
              left: 20.0,
              top: 417.0,
              right: null,
              bottom: null,
              width: 164.0,
              height: 96.0,
              child: GeneratedWidget1174(),
            ),
            Positioned(
              left: 194.0,
              top: 418.0,
              right: null,
              bottom: null,
              width: 164.0,
              height: 96.0,
              child: GeneratedWidget1177(),
            ),
            Positioned(
              left: 24.0,
              top: 131.0,
              right: null,
              bottom: null,
              width: 334.0,
              height: 200.0,
              child: GeneratedWidget1180(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedWidget1182(),
            ),
            Positioned(
              left: 0.0,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget1183(),
            )
          ]),
    ));
  }
}
