import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/get_startapp/generatedwidget2720/generated/GeneratedWidget2727.dart';
import 'package:flutterapp/get_startapp/generatedwidget2720/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget2720/generated/GeneratedWidget2721.dart';

/* Frame 成績彈出式
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget2720 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 144.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 90, 200, 250),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.9166666666666666;

                        final double height =
                            constraints.maxHeight * 0.21921182266009853;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.041666666666666664,
                              y: constraints.maxHeight * 0.3866995073891626,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedWidget2721(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.9166666666666666;

                        final double height =
                            constraints.maxHeight * 0.21921182266009853;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.041666666666666664,
                              y: constraints.maxHeight * 0.16379310344827586,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedWidget2727(),
                              ))
                        ]);
                      }),
                    )
                  ]),
            ),
            Positioned(
              left: null,
              top: 50.0,
              right: null,
              bottom: null,
              width: 120.0,
              height: 80.0,
              child: GeneratedGroup1Widget(),
            )
          ]),
    ));
  }
}
