import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget285/generated/GeneratedWidget332.dart';
import 'package:flutterapp/get_startapp/generatedwidget285/generated/GeneratedWidget321.dart';
import 'package:flutterapp/get_startapp/generatedwidget285/generated/GeneratedWidget296.dart';
import 'package:flutterapp/get_startapp/generatedwidget285/generated/GeneratedWidget316.dart';
import 'package:flutterapp/get_startapp/generatedwidget285/generated/GeneratedWidget306.dart';
import 'package:flutterapp/get_startapp/generatedwidget285/generated/GeneratedWidget301.dart';
import 'package:flutterapp/get_startapp/generatedwidget285/generated/GeneratedWidget311.dart';
import 'package:flutterapp/get_startapp/generatedwidget285/generated/GeneratedWidget291.dart';
import 'package:flutterapp/get_startapp/generatedwidget285/generated/GeneratedWidget286.dart';

/* Frame 校園快訊-主頁
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget285 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1032.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 1032.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 38.0,
                                    top: 413.0,
                                    right: null,
                                    bottom: null,
                                    width: 300.0,
                                    height: 107.0,
                                    child: GeneratedWidget286(),
                                  ),
                                  Positioned(
                                    left: 38.0,
                                    top: 667.0,
                                    right: null,
                                    bottom: null,
                                    width: 300.0,
                                    height: 107.0,
                                    child: GeneratedWidget291(),
                                  ),
                                  Positioned(
                                    left: 38.0,
                                    top: 794.0,
                                    right: null,
                                    bottom: null,
                                    width: 300.0,
                                    height: 107.0,
                                    child: GeneratedWidget296(),
                                  ),
                                  Positioned(
                                    left: 38.0,
                                    top: 540.0,
                                    right: null,
                                    bottom: null,
                                    width: 300.0,
                                    height: 107.0,
                                    child: GeneratedWidget301(),
                                  ),
                                  Positioned(
                                    left: 38.0,
                                    top: 286.0,
                                    right: null,
                                    bottom: null,
                                    width: 300.0,
                                    height: 107.0,
                                    child: GeneratedWidget306(),
                                  ),
                                  Positioned(
                                    left: -3464.0,
                                    top: -1471.0,
                                    right: null,
                                    bottom: null,
                                    width: 300.0,
                                    height: 107.0,
                                    child: GeneratedWidget311(),
                                  ),
                                  Positioned(
                                    left: 38.0,
                                    top: 159.0,
                                    right: null,
                                    bottom: null,
                                    width: 300.0,
                                    height: 107.0,
                                    child: GeneratedWidget316(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: -2.2737367544323206e-13,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget321(),
            ),
            Positioned(
              left: null,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 139.0,
              child: GeneratedWidget332(),
            )
          ]),
    ));
  }
}
