import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generated6widget4/generated/GeneratedWidget1604.dart';
import 'package:flutterapp/get_startapp/generated6widget4/generated/GeneratedWidget1591.dart';
import 'package:flutterapp/get_startapp/generated6widget4/generated/GeneratedWidget1593.dart';
import 'package:flutterapp/get_startapp/generated6widget4/generated/GeneratedWidget1592.dart';
import 'package:flutterapp/get_startapp/generated6widget4/generated/Generated20201202Widget4.dart';

/* Frame 公佈欄6
    Autogenerated by FlutLab FTF Generator
  */
class Generated6Widget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 35.0,
                      top: 235.0,
                      right: null,
                      bottom: null,
                      width: 127.0,
                      height: 46.0,
                      child: GeneratedWidget1591(),
                    ),
                    Positioned(
                      left: 185.0,
                      top: 235.0,
                      right: null,
                      bottom: null,
                      width: 184.0,
                      height: 46.0,
                      child: Generated20201202Widget4(),
                    ),
                    Positioned(
                      left: 20.0,
                      top: 297.0,
                      right: null,
                      bottom: null,
                      width: 342.0,
                      height: 297.0,
                      child: GeneratedWidget1592(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget1593(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 225.0,
              child: GeneratedWidget1604(),
            )
          ]),
    ));
  }
}
