import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget1209/generated/GeneratedWidget1210.dart';
import 'package:flutterapp/get_startapp/generatedwidget1209/generated/GeneratedWidget1211.dart';
import 'package:flutterapp/get_startapp/generatedwidget1209/generated/GeneratedWidget1213.dart';

/* Frame 待開發
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget1209 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 83.0,
                      top: 330.0,
                      right: null,
                      bottom: null,
                      width: 214.0,
                      height: 81.0,
                      child: GeneratedWidget1210(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 139.0,
                      child: GeneratedWidget1211(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget1213(),
            )
          ]),
    ));
  }
}
