import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generated1widget49/generated/Generated122511020Widget1.dart';
import 'package:flutterapp/get_startapp/generated1widget49/generated/GeneratedWidget1664.dart';
import 'package:flutterapp/get_startapp/generated1widget49/generated/Generated20201202Widget7.dart';
import 'package:flutterapp/get_startapp/generated1widget49/generated/GeneratedWidget1665.dart';
import 'package:flutterapp/get_startapp/generated1widget49/generated/GeneratedWidget1676.dart';

/* Frame 公佈欄1
    Autogenerated by FlutLab FTF Generator
  */
class Generated1Widget49 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 925.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 925.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 297.0,
                                    right: null,
                                    bottom: null,
                                    width: 342.0,
                                    height: 297.0,
                                    child: Generated122511020Widget1(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 235.0,
                                    right: null,
                                    bottom: null,
                                    width: 127.0,
                                    height: 46.0,
                                    child: GeneratedWidget1664(),
                                  ),
                                  Positioned(
                                    left: 170.0,
                                    top: 235.0,
                                    right: null,
                                    bottom: null,
                                    width: 184.0,
                                    height: 46.0,
                                    child: Generated20201202Widget7(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: -2.2737367544323206e-13,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget1665(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 225.0,
              child: GeneratedWidget1676(),
            )
          ]),
    ));
  }
}
