import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget2719/generated/Generated4Widget8.dart';
import 'package:flutterapp/get_startapp/generatedwidget2719/generated/Generated3Widget8.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/get_startapp/generatedwidget2719/generated/Generated2Widget9.dart';
import 'package:flutterapp/get_startapp/generatedwidget2719/generated/Generated1Widget93.dart';
import 'package:flutterapp/get_startapp/generatedwidget2719/generated/Generated9Widget4.dart';
import 'package:flutterapp/get_startapp/generatedwidget2719/generated/Generated7Widget4.dart';
import 'package:flutterapp/get_startapp/generatedwidget2719/generated/Generated5Widget8.dart';
import 'package:flutterapp/get_startapp/generatedwidget2719/generated/Generated8Widget4.dart';
import 'package:flutterapp/get_startapp/generatedwidget2719/generated/Generated11Widget2.dart';
import 'package:flutterapp/get_startapp/generatedwidget2719/generated/Generated6Widget6.dart';
import 'package:flutterapp/get_startapp/generatedwidget2719/generated/Generated10Widget1.dart';
import 'package:flutterapp/get_startapp/generatedwidget2719/generated/Generated12Widget3.dart';

/* Instance 月份
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget2719 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 75.0,
      height: 480.0,
      decoration: BoxDecoration(
        border: Border.all(
          width: 1.2999999523162842,
          color: Color.fromARGB(255, 0, 0, 0),
        ),
        gradient: LinearGradient(
          begin: Alignment(0.0, -1.0),
          end: Alignment(0.0, 0.9999999999999998),
          stops: [0.0, 1.0],
          colors: [
            Color.fromARGB(255, 255, 255, 255),
            Color.fromARGB(0, 255, 255, 255)
          ],
        ),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 240, 240, 240),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated1Widget93(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.08333333333333333,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated2Widget9(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.16666666666666666,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated3Widget8(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.25,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated4Widget8(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.3333333333333333,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated5Widget8(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.4166666666666667,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated6Widget6(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.5,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated7Widget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.5833333333333334,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated8Widget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.6666666666666666,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated9Widget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.75,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated10Widget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.8333333333333334,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated11Widget2(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 1.0666666666666667;

                final double height = constraints.maxHeight * 0.09375;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.9166666666666666,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: Generated12Widget3(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
