import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget454/generated/GeneratedWidget455.dart';
import 'package:flutterapp/get_startapp/generatedwidget454/generated/GeneratedWidget458.dart';
import 'package:flutterapp/get_startapp/generatedwidget454/generated/GeneratedWidget456.dart';

/* Frame 設定-關於-通知開
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget454 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 40.0,
                      top: 271.0,
                      right: null,
                      bottom: null,
                      width: 301.0,
                      height: 27.0,
                      child: GeneratedWidget455(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 139.0,
              child: GeneratedWidget456(),
            ),
            Positioned(
              left: 0.0,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget458(),
            )
          ]),
    ));
  }
}
