import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget1678/generated/GeneratedWidget1714.dart';
import 'package:flutterapp/get_startapp/generatedwidget1678/generated/GeneratedWidget1684.dart';
import 'package:flutterapp/get_startapp/generatedwidget1678/generated/GeneratedWidget1689.dart';
import 'package:flutterapp/get_startapp/generatedwidget1678/generated/GeneratedWidget1709.dart';
import 'package:flutterapp/get_startapp/generatedwidget1678/generated/GeneratedWidget1725.dart';
import 'package:flutterapp/get_startapp/generatedwidget1678/generated/GeneratedWidget1679.dart';
import 'package:flutterapp/get_startapp/generatedwidget1678/generated/GeneratedWidget1694.dart';
import 'package:flutterapp/get_startapp/generatedwidget1678/generated/GeneratedWidget1704.dart';
import 'package:flutterapp/get_startapp/generatedwidget1678/generated/GeneratedWidget1699.dart';

/* Frame 校園快訊-主頁
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget1678 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1032.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 1032.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 38.0,
                                    top: 413.0,
                                    right: null,
                                    bottom: null,
                                    width: 300.0,
                                    height: 107.0,
                                    child: GeneratedWidget1679(),
                                  ),
                                  Positioned(
                                    left: 38.0,
                                    top: 667.0,
                                    right: null,
                                    bottom: null,
                                    width: 300.0,
                                    height: 107.0,
                                    child: GeneratedWidget1684(),
                                  ),
                                  Positioned(
                                    left: 38.0,
                                    top: 794.0,
                                    right: null,
                                    bottom: null,
                                    width: 300.0,
                                    height: 107.0,
                                    child: GeneratedWidget1689(),
                                  ),
                                  Positioned(
                                    left: 38.0,
                                    top: 540.0,
                                    right: null,
                                    bottom: null,
                                    width: 300.0,
                                    height: 107.0,
                                    child: GeneratedWidget1694(),
                                  ),
                                  Positioned(
                                    left: 38.0,
                                    top: 286.0,
                                    right: null,
                                    bottom: null,
                                    width: 300.0,
                                    height: 107.0,
                                    child: GeneratedWidget1699(),
                                  ),
                                  Positioned(
                                    left: -3464.0,
                                    top: -1471.0,
                                    right: null,
                                    bottom: null,
                                    width: 300.0,
                                    height: 107.0,
                                    child: GeneratedWidget1704(),
                                  ),
                                  Positioned(
                                    left: 38.0,
                                    top: 159.0,
                                    right: null,
                                    bottom: null,
                                    width: 300.0,
                                    height: 107.0,
                                    child: GeneratedWidget1709(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget1714(),
            ),
            Positioned(
              left: null,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 139.0,
              child: GeneratedWidget1725(),
            )
          ]),
    ));
  }
}
