import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget1486/generated/Generated108Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget1486/generated/Generated109Widget7.dart';
import 'package:flutterapp/get_startapp/generatedwidget1486/generated/Generated109Widget8.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/get_startapp/generatedwidget1486/generated/Generated108Widget1.dart';

/* Frame 學期下拉式選單
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget1486 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.only(
        topLeft: Radius.circular(0.0),
        topRight: Radius.circular(0.0),
        bottomRight: Radius.circular(20.0),
        bottomLeft: Radius.circular(20.0),
      ),
      child: Container(
        width: 169.0,
        height: 163.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(0.0),
            topRight: Radius.circular(0.0),
            bottomRight: Radius.circular(20.0),
            bottomLeft: Radius.circular(20.0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(0.0),
                  topRight: Radius.circular(0.0),
                  bottomRight: Radius.circular(20.0),
                  bottomLeft: Radius.circular(20.0),
                ),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9112426035502958;

                  final double height =
                      constraints.maxHeight * 0.1656441717791411;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.05917159763313609,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated108Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9112426035502958;

                  final double height =
                      constraints.maxHeight * 0.1656441717791411;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.05917159763313609,
                        y: constraints.maxHeight * 0.25766871165644173,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated108Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9112426035502958;

                  final double height =
                      constraints.maxHeight * 0.1656441717791411;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.05917159763313609,
                        y: constraints.maxHeight * 0.5153374233128835,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated109Widget7(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9112426035502958;

                  final double height =
                      constraints.maxHeight * 0.1656441717791411;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.05917159763313609,
                        y: constraints.maxHeight * 0.7730061349693251,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated109Widget8(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
