import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedp1widget1/generated/GeneratedWidget1766.dart';
import 'package:flutterapp/get_startapp/generatedp1widget1/generated/GeneratedWidget1727.dart';
import 'package:flutterapp/get_startapp/generatedp1widget1/generated/GeneratedWidget1742.dart';
import 'package:flutterapp/get_startapp/generatedp1widget1/generated/GeneratedWidget1798.dart';
import 'package:flutterapp/get_startapp/generatedp1widget1/generated/GeneratedWidget1784.dart';
import 'package:flutterapp/get_startapp/generatedp1widget1/generated/GeneratedWidget1736.dart';
import 'package:flutterapp/get_startapp/generatedp1widget1/generated/GeneratedWidget1778.dart';
import 'package:flutterapp/get_startapp/generatedp1widget1/generated/GeneratedWidget1760.dart';
import 'package:flutterapp/get_startapp/generatedp1widget1/generated/GeneratedWidget1772.dart';
import 'package:flutterapp/get_startapp/generatedp1widget1/generated/GeneratedWidget1787.dart';
import 'package:flutterapp/get_startapp/generatedp1widget1/generated/GeneratedWidget1751.dart';

/* Frame 公布欄-P1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedP1Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1032.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 1032.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 228.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 88.0,
                                    child: GeneratedWidget1727(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 140.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 88.0,
                                    child: GeneratedWidget1736(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 316.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 88.0,
                                    child: GeneratedWidget1742(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 404.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 88.0,
                                    child: GeneratedWidget1751(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 580.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 88.0,
                                    child: GeneratedWidget1760(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 492.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 88.0,
                                    child: GeneratedWidget1766(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 668.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 88.0,
                                    child: GeneratedWidget1772(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 756.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 88.0,
                                    child: GeneratedWidget1778(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 844.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 88.0,
                                    child: GeneratedWidget1784(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: -2.2737367544323206e-13,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget1787(),
            ),
            Positioned(
              left: null,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 139.0,
              child: GeneratedWidget1798(),
            )
          ]),
    ));
  }
}
