import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/Generated20200230Widget14.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/Generated20200230Widget10.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/Generated20200230Widget12.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedVector9Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget537.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget517.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedVector3Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedVector4Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget531.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget480.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget478.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget495.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget525.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedVector7Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget523.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget482.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/Generated20200230Widget2.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget511.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget507.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget509.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedVector5Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget533.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/Generated20200230Widget16.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget501.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/Generated20200230Widget6.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget521.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget499.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedVector1Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget505.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedVector8Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedVector2Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget513.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget519.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget484.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget515.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget474.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget529.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget472.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedVector6Widget.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget527.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget476.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget497.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/Generated20200230Widget8.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget503.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/Generated20200230Widget4.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget535.dart';
import 'package:flutterapp/get_startapp/generatedwidget469/generated/GeneratedWidget470.dart';

/* Frame 缺曠/請假-主頁
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget469 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 196.0,
                      right: null,
                      bottom: null,
                      width: 71.0,
                      height: 16.0,
                      child: Generated20200230Widget2(),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 71.0,
                      height: 16.0,
                      child: Generated20200230Widget4(),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 250.0,
                      right: null,
                      bottom: null,
                      width: 71.0,
                      height: 16.0,
                      child: Generated20200230Widget6(),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 277.0,
                      right: null,
                      bottom: null,
                      width: 71.0,
                      height: 16.0,
                      child: Generated20200230Widget8(),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 304.0,
                      right: null,
                      bottom: null,
                      width: 71.0,
                      height: 16.0,
                      child: Generated20200230Widget10(),
                    ),
                    Positioned(
                      left: 224.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 0.0,
                      height: 537.0,
                      child: GeneratedVector1Widget(),
                    ),
                    Positioned(
                      left: 249.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 0.0,
                      height: 537.0,
                      child: GeneratedVector6Widget(),
                    ),
                    Positioned(
                      left: 274.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 0.0,
                      height: 537.0,
                      child: GeneratedVector7Widget(),
                    ),
                    Positioned(
                      left: 299.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 0.0,
                      height: 537.0,
                      child: GeneratedVector8Widget(),
                    ),
                    Positioned(
                      left: 324.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 0.0,
                      height: 537.0,
                      child: GeneratedVector9Widget(),
                    ),
                    Positioned(
                      left: 149.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 0.0,
                      height: 537.0,
                      child: GeneratedVector2Widget(),
                    ),
                    Positioned(
                      left: 124.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 0.0,
                      height: 537.0,
                      child: GeneratedVector5Widget(),
                    ),
                    Positioned(
                      left: 199.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 0.0,
                      height: 537.0,
                      child: GeneratedVector4Widget(),
                    ),
                    Positioned(
                      left: 174.0,
                      top: 170.0,
                      right: null,
                      bottom: null,
                      width: 0.0,
                      height: 537.0,
                      child: GeneratedVector3Widget(),
                    ),
                    Positioned(
                      left: 106.0,
                      top: 196.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget470(),
                    ),
                    Positioned(
                      left: 131.0,
                      top: 196.0,
                      right: null,
                      bottom: null,
                      width: 12.0,
                      height: 16.0,
                      child: GeneratedWidget472(),
                    ),
                    Positioned(
                      left: 106.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget474(),
                    ),
                    Positioned(
                      left: 206.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget476(),
                    ),
                    Positioned(
                      left: 156.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget478(),
                    ),
                    Positioned(
                      left: 181.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget480(),
                    ),
                    Positioned(
                      left: 131.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget482(),
                    ),
                    Positioned(
                      left: 106.0,
                      top: 174.0,
                      right: null,
                      bottom: null,
                      width: 239.0,
                      height: 13.0,
                      child: GeneratedWidget484(),
                    ),
                    Positioned(
                      left: 231.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget495(),
                    ),
                    Positioned(
                      left: 256.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget497(),
                    ),
                    Positioned(
                      left: 281.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget499(),
                    ),
                    Positioned(
                      left: 306.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget501(),
                    ),
                    Positioned(
                      left: 331.0,
                      top: 223.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget503(),
                    ),
                    Positioned(
                      left: 231.0,
                      top: 250.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget505(),
                    ),
                    Positioned(
                      left: 206.0,
                      top: 277.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget507(),
                    ),
                    Positioned(
                      left: 281.0,
                      top: 304.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget509(),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 71.0,
                      height: 16.0,
                      child: Generated20200230Widget12(),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 358.0,
                      right: null,
                      bottom: null,
                      width: 71.0,
                      height: 16.0,
                      child: Generated20200230Widget14(),
                    ),
                    Positioned(
                      left: 21.0,
                      top: 385.0,
                      right: null,
                      bottom: null,
                      width: 71.0,
                      height: 16.0,
                      child: Generated20200230Widget16(),
                    ),
                    Positioned(
                      left: 106.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget511(),
                    ),
                    Positioned(
                      left: 131.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget513(),
                    ),
                    Positioned(
                      left: 156.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget515(),
                    ),
                    Positioned(
                      left: 181.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget517(),
                    ),
                    Positioned(
                      left: 206.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget519(),
                    ),
                    Positioned(
                      left: 231.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget521(),
                    ),
                    Positioned(
                      left: 256.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget523(),
                    ),
                    Positioned(
                      left: 281.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget525(),
                    ),
                    Positioned(
                      left: 306.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget527(),
                    ),
                    Positioned(
                      left: 331.0,
                      top: 331.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget529(),
                    ),
                    Positioned(
                      left: 156.0,
                      top: 358.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget531(),
                    ),
                    Positioned(
                      left: 181.0,
                      top: 390.0,
                      right: null,
                      bottom: null,
                      width: 14.0,
                      height: 16.0,
                      child: GeneratedWidget533(),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 139.0,
              child: GeneratedWidget535(),
            ),
            Positioned(
              left: 0.0,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget537(),
            )
          ]),
    ));
  }
}
