import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generated6widget1/generated/Generated20201202Widget.dart';
import 'package:flutterapp/get_startapp/generated6widget1/generated/GeneratedWidget200.dart';
import 'package:flutterapp/get_startapp/generated6widget1/generated/GeneratedWidget211.dart';
import 'package:flutterapp/get_startapp/generated6widget1/generated/GeneratedWidget199.dart';
import 'package:flutterapp/get_startapp/generated6widget1/generated/GeneratedWidget198.dart';

/* Frame 公佈欄6
    Autogenerated by FlutLab FTF Generator
  */
class Generated6Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/Generated2Widget2'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Container(
                width: 375.0,
                height: 812.0,
                child: Stack(
                    fit: StackFit.expand,
                    alignment: Alignment.center,
                    overflow: Overflow.visible,
                    children: [
                      ClipRRect(
                        borderRadius: BorderRadius.zero,
                        child: Container(
                          color: Color.fromARGB(255, 255, 255, 255),
                        ),
                      ),
                      Positioned(
                        left: 35.0,
                        top: 235.0,
                        right: null,
                        bottom: null,
                        width: 127.0,
                        height: 46.0,
                        child: GeneratedWidget198(),
                      ),
                      Positioned(
                        left: 185.0,
                        top: 235.0,
                        right: null,
                        bottom: null,
                        width: 184.0,
                        height: 46.0,
                        child: Generated20201202Widget(),
                      ),
                      Positioned(
                        left: 20.0,
                        top: 297.0,
                        right: null,
                        bottom: null,
                        width: 342.0,
                        height: 297.0,
                        child: GeneratedWidget199(),
                      )
                    ]),
              ),
              Positioned(
                left: 0.0,
                top: 730.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 82.0,
                child: GeneratedWidget200(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 225.0,
                child: GeneratedWidget211(),
              )
            ]),
      ),
    ));
  }
}
