import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generatedwidget5/generated/GeneratedLargeTitleWidget.dart';
import 'package:flutterapp/get_startapp/generatedwidget5/generated/GeneratedLeftTitleRightWidget.dart';
import 'package:flutterapp/get_startapp/generatedwidget5/generated/GeneratedIPhoneXornewerWidget.dart';

/* Component 快訊標題狀態欄
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 175.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 0, 80, 239),
              ),
            ),
            Positioned(
              left: 20.0,
              top: 106.0,
              right: 7.0,
              bottom: null,
              width: null,
              height: 46.0,
              child: GeneratedLargeTitleWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 45.0,
              right: 0.0,
              bottom: null,
              width: null,
              height: 42.0,
              child: GeneratedLeftTitleRightWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: null,
              width: null,
              height: 44.0,
              child: GeneratedIPhoneXornewerWidget(),
            )
          ]),
    ));
  }
}
