import 'package:flutter/material.dart';

/* Text Text
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTextWidget16 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Align(
      alignment: Alignment.center,
      child: Text(
        ''' ''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: TextStyle(
          height: 1.0,
          fontSize: 22.0,
          fontFamily: 'SF Pro Text',
          fontWeight: FontWeight.w400,
          color: Color.fromARGB(255, 0, 0, 0),

          /* letterSpacing: -0.40799999237060547, */
        ),
      ),
    ));
  }
}
