import 'package:flutter/material.dart';
import 'package:flutterapp/get_startapp/generated3widget6/generated/GeneratedhttpsformsgleH1cANhbzVfwVwzRP711012510912912001211292ht1.dart';
import 'package:flutterapp/get_startapp/generated3widget6/generated/Generated20201130Widget1.dart';
import 'package:flutterapp/get_startapp/generated3widget6/generated/GeneratedWidget1648.dart';
import 'package:flutterapp/get_startapp/generated3widget6/generated/GeneratedWidget1636.dart';
import 'package:flutterapp/get_startapp/generated3widget6/generated/GeneratedWidget1637.dart';

/* Frame 公佈欄3
    Autogenerated by FlutLab FTF Generator
  */
class Generated3Widget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1171.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 1171.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 297.0,
                                    right: null,
                                    bottom: null,
                                    width: 339.0,
                                    height: 294.0,
                                    child:
                                        GeneratedhttpsformsgleH1cANhbzVfwVwzRP711012510912912001211292ht1(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 235.0,
                                    right: null,
                                    bottom: null,
                                    width: 127.0,
                                    height: 46.0,
                                    child: GeneratedWidget1636(),
                                  ),
                                  Positioned(
                                    left: 185.0,
                                    top: 235.0,
                                    right: null,
                                    bottom: null,
                                    width: 184.0,
                                    height: 46.0,
                                    child: Generated20201130Widget1(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: -1.1368683772161603e-13,
              top: 730.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 82.0,
              child: GeneratedWidget1637(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 225.0,
              child: GeneratedWidget1648(),
            )
          ]),
    ));
  }
}
